server:
  port: 8888
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        namespace: 74050d70-8234-4c7b-85af-2626f9801fe3
        group: DEFAULT_GROUP
        server-addr: localhost:8848
      config:
        bootstrap:
          enable: true
        file-extension: yml
        namespace: 74050d70-8234-4c7b-85af-2626f9801fe3
        auto-refresh: true
        enable-remote-sync-config: true
        timeout: 3000
        group: DEFAULT_GROUP
        refresh-enabled: true
        server-addr: localhost:8848
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 2  #流速 每秒
            redis-rate-limiter.burstCapacity: 10   #令牌桶的容积
            rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
            key-resolver: "#{@apiKeyResolver}" #SPEL表达式去的对应的bean
  redis:
    port: 6379
    host: localhost
    username: java
    password: 123456
    timeout: 3000
    lettuce:
      pool:
        max-active: 300
        min-idle: 0
        max-idle: 100